BEGIN TRANSACTION;

-- Table preferences
CREATE TABLE IF NOT EXISTS `preferences` ( 
    `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `libelle` VARCHAR ( 128 ),
    `value` TEXT
);
-- Content:
INSERT INTO `preferences` (`libelle`, `value`) VALUES 
    ("LANGUAGE", "AR"),
    ("SELECTED_DB", ""),
    ("SELECTED_DB_DIR", ""),
    ("SELECTED_TEMPLATE", "1"),
    ("OUTPUT_DIR", ""),
    ("XL_EXPORT", "Y"),
    ("PDF_EXPORT", "Y"),
    ("ONE_FILE_PER_GROUP", "N"),
    ("TWO_SHEETS_PER_GROUP", "N"),
    ("TPL1_CATEGORY", "LIST"),
    ("TPL1_INFOS", "NUMERO|COMMA| |AND|CODE|COMMA| |AND|FULL_NAME|COMMA| |AND|GENDER|COMMA| |AND|BIRTH_DATE| |LAST_AND|BIRTH_PLACE|."),
    ("TPL1_TITLE", "لائحة قســــم"),
    ("TPL1_BOLDER_NAMES", "Y"),
    ("TPL1_NAMES_ALIGN", "C"),
    ("TPL1_SCHOOL_INFOS_SEPARATOR", "   |   "),
    ("TPL1_CUSTOM_STRING", "ملاحظات"),
    ("TPL2_CATEGORY", "LIST"),
    ("TPL2_INFOS", "NUMERO|COMMA| |AND|CODE|COMMA| |AND|FIRST_NAME| |LAST_AND|LAST_NAME|."),
    ("TPL2_TITLE", "لائحة قســــم"),
    ("TPL2_CUSTOM_STRING", "ملاحظات"),
    ("TPL2_BOLDER_NAMES", "Y"),
    ("TPL2_NAMES_ALIGN", "C"),
    ("TPL3_INFOS", "NUMERO|COMMA| |AND|CODE|COMMA| |AND|FIRST_NAME|COMMA| |AND|LAST_NAME|COMMA| |AND|GENDER|COMMA| |AND|BIRTH_DATE| |LAST_AND|BIRTH_PLACE|."),
    ("TPL3_CATEGORY", "LIST"),
    ("TPL3_TITLE", "لائحة قســــم"),
    ("TPL3_CUSTOM_STRING", "ملاحظات"),
    ("TPL3_BOLDER_NAMES", "Y"),
    ("TPL3_NAMES_ALIGN", "C"),
    ("TPL4_INFOS", "NUMERO|COMMA| |AND|CODE|COMMA| |AND|FIRST_NAME| |LAST_AND|LAST_NAME|."),
    ("TPL4_CATEGORY", "MARKS_SHEET"),
    ("TPL4_TITLE", "ورقة التنقيط"),
    ("TPL4_CUSTOM_STRING", "ملاحظات"),
    ("TPL4_BOLDER_NAMES", "Y"),
    ("TPL4_NAMES_ALIGN", "C"),
    ("TPL5_INFOS", "NUMERO|COMMA| |AND|CODE|COMMA| |AND|FIRST_NAME| |LAST_AND|LAST_NAME|."),
    ("TPL5_CATEGORY", "MARKS_SHEET"),
    ("TPL5_TITLE", "ورقة التنقيط"),
    ("TPL5_BOLDER_NAMES", "Y"),
    ("TPL5_NAMES_ALIGN", "C"),
    ("TPL6_INFOS", "NUMERO|COMMA| |AND|CODE| |LAST_AND|FULL_NAME|."),
    ("TPL6_CATEGORY", "MARKS_SHEET"),
    ("TPL6_TITLE", "ورقة تنقيط"),
    ("TPL6_CUSTOM_STRING", "ملاحظات"),
    ("TPL6_BOLDER_NAMES", "Y"),
    ("TPL6_SCHOOL_INFOS_SEPARATOR", "   |   "),
    ("TPL6_NAMES_ALIGN", "C"),
    ("TPL7_INFOS", "NONE|."),
    ("TPL7_CATEGORY", "ABSENCE_SHEET"),
    ("TPL7_SCHOOL_INFOS_SEPARATOR", "NL"),
    ("TPL7_FIRST_DAY_OF_WEEK", "1"),
    ("TPL7_SELECTED_WEEK", "1"),
    ("TPL7_TITLE", "ورقة الغياب الأسبوعية"),
    ("TPL7_TO_ADMINISTRATION", "تلاميذ يوجهون للإدارة"),
    ("TPL7_YEAR", "السنة الدراسية: "),
    ("TPL8_INFOS", "NONE|."),
    ("TPL8_CATEGORY", "ABSENCE_SHEET"),
    ("TPL8_SCHOOL_INFOS_SEPARATOR", "NL"),
    ("TPL8_MESSAGE", "المرجو من السيدات والسادة الأساتذة الكرام عدم قبول أي تلميذ(ة) متغيب(ة) في حصة أو حصص سابقة إلا بإذن من الحراسة العامة للخارجية. والمرجو أيضا إرسال ملف الغياب إلى مكتب الحراسة العامة قبل نهاية آخر حصة مسائية بنصف ساعة. شكرا على تعاونكم."),
    ("TPL8_FIRST_DAY_OF_WEEK", "1"),
    ("TPL8_SELECTED_WEEK", "1"),
    ("TPL8_TITLE", "ورقة الغياب الأسبوعية"),
    ("TPL8_TO_ADMINISTRATION", "تلاميذ يوجهون للإدارة"),
    ("TPL8_YEAR", "السنة الدراسية:"),
    ("TPL9_INFOS", "NUMERO| |LAST_AND|FULL_NAME|."),
    ("TPL9_CATEGORY", "ABSENCE_SHEET"),
    ("TPL9_BOLDER_NAMES", "Y"),
    ("TPL9_FIRST_DAY_OF_WEEK", "1"),
    ("TPL9_SELECTED_WEEK", "1"),
    ("TPL9_TITLE", "ورقة الغياب الأسبوعية"),
    ("TPL9_TO_ADMINISTRATION", "تلاميذ يوجهون للإدارة"),
    ("TPL9_SIGNATURE", "توقيع الأستاذ"),
    ("TPL9_NAMES_ALIGN", "C"),
    ("TPL10_INFOS", "NUMERO| |LAST_AND|FULL_NAME|."),
    ("TPL10_CATEGORY", "ABSENCE_SHEET"),
    ("TPL10_BOLDER_NAMES", "Y"),
    ("TPL10_FIRST_DAY_OF_WEEK", "1"),
    ("TPL10_SELECTED_WEEK", "1"),
    ("TPL10_TITLE", "ورقة الغياب الأسبوعية"),
    ("TPL10_TO_ADMINISTRATION", "تلاميذ يوجهون للإدارة"),
    ("TPL10_SIGNATURE", "توقيع الأستاذ"),
    ("TPL10_NAMES_ALIGN", "C"),
    ("ABSTPL_DAY_1_MORNING_GRAYED", "N"),
    ("ABSTPL_DAY_2_MORNING_GRAYED", "N"),
    ("ABSTPL_DAY_3_MORNING_GRAYED", "N"),
    ("ABSTPL_DAY_4_MORNING_GRAYED", "N"),
    ("ABSTPL_DAY_5_MORNING_GRAYED", "N"),
    ("ABSTPL_DAY_6_MORNING_GRAYED", "N"),
    ("ABSTPL_DAY_1_AFTERNOON_GRAYED", "N"),
    ("ABSTPL_DAY_2_AFTERNOON_GRAYED", "N"),
    ("ABSTPL_DAY_3_AFTERNOON_GRAYED", "N"),
    ("ABSTPL_DAY_4_AFTERNOON_GRAYED", "N"),
    ("ABSTPL_DAY_5_AFTERNOON_GRAYED", "N"),
    ("ABSTPL_DAY_6_AFTERNOON_GRAYED", "N"),
    ("ABSTPL_MORNING", "الفترة الصباحية"),
    ("ABSTPL_MORNING_1", "ص 1"),
    ("ABSTPL_MORNING_2", "ص 2"),
    ("ABSTPL_MORNING_3", "ص 3"),
    ("ABSTPL_MORNING_4", "ص 4"),
    ("ABSTPL_AFTERNOON", "فترة بعد الزوال"),
    ("ABSTPL_AFTERNOON_1", "م 1"),
    ("ABSTPL_AFTERNOON_2", "م 2"),
    ("ABSTPL_AFTERNOON_3", "م 3"),
    ("ABSTPL_AFTERNOON_4", "م 4"),
    ("ABSTPL_DAY_0", "الأحد"),
    ("ABSTPL_DAY_1", "الإثنين"),
    ("ABSTPL_DAY_2", "الثلاثاء"),
    ("ABSTPL_DAY_3", "الأربعاء"),
    ("ABSTPL_DAY_4", "الخميس"),
    ("ABSTPL_DAY_5", "الجمعة"),
    ("ABSTPL_DAY_6", "السبت"),
    ("ABSTPL_FROM", "من"),
    ("ABSTPL_TO", "إلى"),
    ("WEEKS_RANGE_SIZE", "9"),
    ("MW_LAST_STATE_X", ""),
    ("MW_LAST_STATE_Y", ""),
    ("MW_LAST_STATE_W", ""),
    ("MW_LAST_STATE_H", ""),
    ("GENERATIONS_COUNTER", "")
;

COMMIT;